### ISSUE TITLE
main part of algorithm

### ISSUE THREAD

**Issue by andreasbinder** [hiwonjoon/ICML2019-TREX#7]
I really enjoyed reading your paper as I think it has great potential! I wanted to try out the code myself but the repo is quite huge. I mainly wanted to know where I can find the main part of the TREX algorithm in the repo (director/file) to get a better grasp how it works :) thanks a lot in advance!

**Comment by dsbrown1331** [comment]
Glad you enjoyed the paper. I'd start here: [LearnAtariReward.py](https://github.com/hiwonjoon/ICML2019-TREX/blob/master/atari/LearnAtariReward.py) This module has all the code for training the reward network via a ranking consisting of pairwise preferences. See the [README](https://github.com/hiwonjoon/ICML2019-TREX/blob/master/atari/README.md) for an example of how to run it with synthetic demos.

**Comment by andreasbinder** [comment]
Thanks a lot! 
Also I was wondering whether there exists the possability to visualize the mujoco results to check the process. Thank you for your effort!
